// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emikorypgvtqiecftmoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtaWtvcnlwZ3Z0cWllY2Z0bW9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NTAzNTIsImV4cCI6MjA3MzAyNjM1Mn0.4IRAHOD_A-qcYdskwE_F3Ssyru2YsH7cEs9B1pYy5Uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});